version: "1.0"

volumes:
  mysql_data:
    driver: local

services:
  database:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - ./:/app/
    environment:
      MYSQL_DATABASE: fruitsalad
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - internal

  app:
    container_name: Backend
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - ./:/app/app
    links:
      - database
    networks:
      - internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: database
      DB_DATABASE: fruitsalad
      DB_USER: root
      DB_PASSWORD: 1234
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      #KEYCLOAK_ADMIN: admin
      #KEYCLOAK_ADMIN_PASSWORD: admin
      #KC_HOSTNAME_ADMIN_URL: http://localhost:8085
    ports:
      - 8085:8085
    depends_on:
      - database
    command: start-dev

networks:
  internal:
    name: internal