version: "3.9"

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./:/fruitSalad/
    environment:
      MYSQL_DATABASE: fruitsalad
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - internal

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.2-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: fruitsalad
      DB_USER: root
      DB_PASSWORD: 1234
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:8081
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    command: start-dev --http-port 8081

networks:
  internal:
    name: internal