version: "3.9"

volumes:
  mysql_data:
    driver: local

services:
  cart:
    container_name: cart
    command: java -jar target/Cart-0.0.1-SNAPSHOT.jar
    build:
      context: cart
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/cart/app
    networks:
      - internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fruitsalad?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672

  checkout:
    container_name: checkout
    command: java -jar target/Checkout-0.0.1-SNAPSHOT.jar
    build:
      context: checkout
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./:/checkout/app
    networks:
      - internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fruitsalad?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672

  payment:
    container_name: payment
    command: java -jar target/Payment-0.0.1-SNAPSHOT.jar
    build:
      context: payment
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./:/payment/app
    networks:
      - internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fruitsalad?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./:/fruitSalad/
    environment:
      MYSQL_DATABASE: fruitsalad
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - internal

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.2-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: fruitsalad
      DB_USER: root
      DB_PASSWORD: 1234
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:8081
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    command: start-dev --http-port 8081

networks:
  internal:
    name: internal
