version: "3.9"

volumes:
  mysql_data:
    driver: local

services:
  app:
    container_name: cart
    command: java -jar target/Cart-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/cart/app
    networks:
      - internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fruitsalad?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672

networks:
  internal:
    name: internal